### ISSUE TITLE
single-dropdown selection of false :id value

### ISSUE THREAD

**Issue by jcthalys** [day8/re-com#162] opened 2017-09-14 17:35 UTC
Hi!
I would like to understand if this is really an issue or not.

When you select **Partners** the id with a **false value**, the _dropdown_ does not leave the selection on the screen instead it **Owner** works perfectly.

```clojure
(let [equipment-is-owner? (reagent/atom false)]
                [re-com/single-dropdown
                 :width "220px"
                 :choices [{:id true :label "Owner"}
                           {:id false :label "Partners"}]
                 :model equipment-is-owner?
                 :on-change #(swap! equipment-is-owner? not)])
```

**Comment by MawiraIke** [comment] 2022-01-20 16:47
This issue seems to be caused by [this line](https://github.com/day8/re-com/blob/master/src/re_com/dropdown.cljs#L210) which fails when the value of the `model` is `false`. Currently the selection is actually made but the choice is not displayed. Having a placeholder passed to the dropdown will default to showing the `placeholder` instead. Also, changing the check from  `(if @internal-model ...)` to `(if (some? @internal-model) ...)` fixes the issue.
Pushing a fix for this.

**Closed** 2022-01-24 00:39 UTC
Labels: bug
