### ISSUE TITLE
Datepicker header height increases when a disabled next or previous year button is displayed

### ISSUE THREAD

**Issue by Gregg8** [day8/re-com#313] opened 2022-01-12 07:36 UTC
Correct header height
![image](https://user-images.githubusercontent.com/3037372/149082774-986cf8c7-afb0-4e17-915b-770bbca07ed7.png)

Increased header height when **disabled** `Next Year` button is shown (same with `Previous Year`)
![image](https://user-images.githubusercontent.com/3037372/149083150-573d4ae0-a00b-41e9-93da-41fdf40dd335.png)

You cannot demonstrate this in the [demo page](https://re-com.day8.com.au/#/date) because it does not allow you to set the `:minimum` or `:maximum` args.

**Comment by MawiraIke** [comment] 2022-01-14 10:32
This issue seems to be caused by padding from [re-com.css](https://github.com/day8/re-com/blob/master/run/resources/public/assets/css/re-com.css#L671) applied to `rc-datepicker-disabled` and `rc-datepicker-unselectable` classes. 
The padding would also be applied to disabled dates but is overwritten by padding from `bootstrap.css`  as shown in the diagram below. Simply, the padding is only used by the following classes in re-com; `rc-datepicker-prev-year`, `rc-datepicker-prev-month`, `rc-datepicker-next-month` and `rc-datepicker-next-year` which are the icons that cause this issue. I would suggest removing the padding from re-com.css.

![preview](https://user-images.githubusercontent.com/38689046/149496508-dc870a06-0542-4e8e-b86f-4ce4da6747e5.png)

Pushing a fix for this.

**Closed** 2022-01-22 12:26 UTC
Labels: bug
