### ISSUE TITLE
Tour component demo breaks on clicking "Start Tour!" button

### ISSUE THREAD

**Issue by zackteo** [day8/re-com#303] opened 2021-08-05 12:10 UTC
As mentioned, https://re-com.day8.com.au/#/tour breaks when the "Start Tour!" button is clicked.

Have tested on both chromium and firefox.

**Comment by MawiraIke** [comment] 2022-01-19 11:14
Upon further investigation, it seems like this issue is caused by the [changes ](https://github.com/day8/re-com/commit/a8e8e72a9b31d3df61b0f4cb6d1fb77bc174b314#diff-9afaa3eb431bca6290434e1e91a842c13b69edadfbbb920b9bcb48bedf969e68R35)done by the `add-at-macro` script. Specifically, the `make-tour-nav` function does not parse its parameters as a map but individually which breaks when we add extra arguments but fail to manually add them in the function parsing as parameters.

Pushing a fix for this issue.

**Closed** 2022-01-22 12:27 UTC
Labels: bug
