### ISSUE TITLE
fn? validator fails for r/partial'ed functions

### ISSUE THREAD

**Issue by dustingetz** [day8/re-com#163] opened 2017-09-18 19:27 UTC
![image](https://user-images.githubusercontent.com/124158/30560402-d67331b0-9c85-11e7-9a51-9013ca209b05.png)

**Comment by dustingetz** [comment] 2017-09-18 19:30
An easier flag to disable the validator macro in debug builds would be helpful also

**Comment by dustingetz** [comment] 2017-09-18 22:27
Paste `goog.DEBUG=false` in dev console to work around this - works for us - not sure the consequences

**Comment by khardenstine** [comment] 2017-10-06 02:40
This was an issue when using reagent < 0.7.0
Their PartialFn did not implement cljs.core.Fn.  This has since changed in release 0.7.0: https://github.com/reagent-project/reagent/pull/303/commits/3cf045dc8264373d93d9c3a7607dc2a349194681

**Comment by mike-thompson-day8** [comment] 2021-02-23 12:40
I'm spring cleaning issues.  This one appears to be very old, and the root cause seems to be outside of re-com and, anyway, is now fixed.  All of which means I'm closing.

**Closed by mike-thompson-day8** 2021-02-23 12:40 UTC
